### PR TITLE
Try out with new aegir

### PR DESCRIPTION
**Pull request by diasdavid**
@dignifiedquire started testing new aegir and found that port 9090 is always used. Can't that be picked at random? https://github.com/ipfs/aegir/issues/139

Node.js tests are passing fine, but browser tests fail with:

```
    AssertionError: expected { isTrusted: [Getter],
  NONE: 0,
  CAPTURING_PHASE: 1,
  AT_TARGET: 2,
  BUBBLING_PHASE: 3,
  type: 'error',
  target:
   { CONNECTING: 0,
     OPEN: 1,
     CLOSING: 2,
     CLOSED: 3,
     url: 'ws://127.0.0.1:9090/',
     readyState: 3,
     bufferedAmount: 0,
     onopen: null,
     onerror: null,
     onclose: null,
     extensions: '',
     protocol: '',
     onmessage: null,
     binaryType: 'arraybuffer',
     close: [Function: close],
     send: [Function: send],
     addEventListener: [Function: addEventListener],
     removeEventListener: [Function: removeEventListener],
     dispatchEvent: [Function: dispatchEvent] },
  currentTarget:
   { CONNECTING: 0,
     OPEN: 1,
     CLOSING: 2,
     CLOSED: 3,
     url: 'ws://127.0.0.1:9090/',
     readyState: 3,
     bufferedAmount: 0,
     onopen: null,
     onerror: null,
     onclose: null,
     extensions: '',
     protocol: '',
     onmessage: null,
     binaryType: 'arraybuffer',
     close: [Function: close],
     send: [Function: send],
     addEventListener: [Function: addEventListener],
     removeEventListener: [Function: removeEventListener],
     dispatchEvent: [Function: dispatchEvent] },
  eventPhase: 0,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  composed: false,
  timeStamp: 210.11500000000004,
  srcElement:
   { CONNECTING: 0,
     OPEN: 1,
     CLOSING: 2,
     CLOSED: 3,
...
```

This doesn't sounds like an aegir problem unless the new updates completely changed the envinronment (websockets) of where tests run. @dignifiedquire ?

### CODE REVIEW

**Comment by diasdavid** [comment]
oh I know

**Comment by diasdavid** [comment]
The logs for browser tests are informative:

```
Test Browser



  3 passing (2s)

Test Webworker



  3 passing (1s)
```

**Comment by dignifiedquire** [comment]
there seems to be a bug in this module, the `dial` callback is called back with an event as the first arg for me when I run this

**Comment by diasdavid** [comment]
@dignifiedquire can you log that event? Not sure where that is coming from but I was also surprised by the bug listed in the first comment.

**Comment by dignifiedquire** [comment]
```
Chrome 60.0.3112 (Mac OS X 10.12.6) LOG: 'connect', '{"isTrusted":true}'
```

**Comment by dignifiedquire** [comment]
@diasdavid also pushed fixes to aegir as well as here, so things are working now. It seems you switched the ports around when migrating from the gulpfile to .aegir, which is why the browser tests were failing.

**Comment by dignifiedquire** [comment]
The error you are listing at the top is the error from failing to connect to the url.

**Comment by diasdavid** [comment]
Ah, forgot to push my commit here:

image

Sorry for the troubles. Let me check this new version :)

**Comment by diasdavid** [comment]
Why does aegir show stats after Node.js but not for the others?

image

**Comment by dignifiedquire** [comment]
Because one is jest and one is karma. The stats are a feature of jest

**Comment by diasdavid** [comment]
Hm.. what do you think about that?

**Comment by dignifiedquire** [comment]
> Hm.. what do you think about that?

about what?

**Comment by diasdavid** [comment]
I mean, do you like how it looks? What do you have in your head as next plans for aegir.next.1 :)

**Comment by dignifiedquire** [comment]
Not much to be honest, changing these outputs would require considerable amounts of work inside karma, jest and aegir.

**Comment by diasdavid** [comment]
Ok. Opened an issue just to preserve the thought https://github.com/ipfs/aegir/issues/144

What's up with codecov? Other than that, seems that aegir is usable and we can upgrade :)

**Comment by dignifiedquire** [comment]
It is enabled by default now. It shows failing because it's the first time we use it

**Pull request merged**
